### ISSUE TITLE
New input to specify a TeX package repository?

### ISSUE THREAD

**Issue by muzimuzhi** [teatimeguest/setup-texlive-action#283]
Which will be passed to [`-repository`](https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-280003.3.1) option of `install-tl` and `tlmgr`.

This would make the result of CI more stable/reproducible.

Use case: retry (by using action [`Wandalen/wretry.action`](https://github.com/Wandalen/wretry.action)) a failed `uses: teatimeguest/setup-texlive-action@v3` step with a static repository, so CI can pass before waiting for any auto-chosen CTAN mirrors to be synced up.

**Comment by teatimeguest** [comment]
Thanks for the suggestion!

A new input `repository` has been added in [v3.1.0](https://github.com/teatimeguest/setup-texlive-action/releases/tag/v3.1.0). Setting this enforces the action to always use the specified repository and suppresses fallback to other repositories.

Example:
```yaml
- uses: teatimeguest/setup-texlive-action@v3
  with:
    repository: https://example.com/path/to/tlnet/
```

There are some limitations at this time:

- Only http/https repositories are supported. This is because the action uses `@actions/http-client` internally, but I am considering adding support for other protocols.
- Versions prior to TeX Live 2012 are not supported because the `tlmgr repository` subcommand is not yet implemented in these versions.
- The TeX Live version of the repository must match the version specified by the action input. Perhaps it might be useful to have an option to always use the remote version?

**Comment by muzimuzhi** [comment]
Many thanks!

Maybe the doc of new input `repository` in README can have an example of the form of URI it expects/supports, or just a link to the TeX Live manual (though I'm a bit afraid the anchor name `x1-280003.3.1` would vary: https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-280003.3.1).

> * The TeX Live version of the repository must match the version specified by the action input. Perhaps it might be useful to have an option to always use the remote version?

Considering the first days after a yearly TeX Live release, yes your suggestion gives the most smooth experience I think.

**Comment by teatimeguest** [comment]
In [`v3.3.0`](https://github.com/teatimeguest/setup-texlive-action/releases/tag/v3.3.0), it is no longer needed to set version explicitly; if set, it will act as an assertion.
